name: Genshin MYS Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - name: Sync with upstream
        if: github.repository != 'Tsuk1ko/genshin-mys-checkin'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
        with:
          upstream_repository: Tsuk1ko/genshin-mys-checkin
          upstream_branch: main
          target_branch: main
          git_pull_args: '-s recursive -Xtheirs'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: cache
          key: gc-cache-v1
          restore-keys: |
            gc-cache-

      - name: Install dependencies
        run: yarn install

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(($RANDOM % 600))

      - name: Checkin
        env:
          COOKIE: ${{ secrets.COOKIE }}
          WB_CONFIG: ${{ secrets.WB_CONFIG }}
        run: yarn start
